### ISSUE TITLE
Attributes containing special characters

### ISSUE THREAD

**Issue by jedireza** [hapijs/confidence#34]
Let's say we have a json document such as:

```json
{
    "things": {
        "sub-thing": "space race"
    }
}
```

I'm getting `undefined` when calling `conf.get('/things/sub-thing')`.

I've tried a handful of escaping attempts. I also quickly scanned the lib but didn't grok anything that seemed relevant to my goal. I also didn't notice any test cases with special characters.

**Comment by patrickkettner** [comment]
Hiya @jedireza!

From the readme...

> key names can only contain alphanumeric characters and '_' with the '$' prefix reserved for special directives

Sorry about that!

**Comment by jedireza** [comment]
Thanks for the reply @patrickkettner
