### ISSUE TITLE
Is it possible to add a key to an object depending on a value ?

### ISSUE THREAD

**Issue by netei** [hapijs/confidence#42]
I would like to have conditionally add the "blipp" subobject to my "plugins" object with a filter.

Have as a result when `phase=LOCAL`: 

    "plugins": {
      "blipp": {
        "showAuth": true
      },
      "other": {
      }
    }

Have as a result when `phase!=LOCAL`: 

    "plugins": {
      "other": {
      }
    }

**Comment by mtharrison** [comment]
I think something like this will work:
```javascript
var Confidence = require('confidence');

var config = {
    plugins: {
        '$filter': 'phase',
        '$base': {
            other: { }
        },
        local: {
            blipp: {
                showAuth: true
            }
        },
        '$default': { }
    }
}

var store = new Confidence.Store(config);

console.log(store.get('/', { phase: 'local' }));                    // { plugins: { other: {}, blipp: { showAuth: true } } }
console.log(store.get('/', { phase: 'something-else' }));   // { plugins: { other: {} } }
```

**Comment by patrickkettner** [comment]
thanks, @mtharrison - that is exactly the way to do this.

lemme know if you have any question, @netei

**Comment by netei** [comment]
Thanks that works well. I wasn't aware of the "$base" key, or at least didn't thought about it.

**Comment by netei** [comment]
Is it possible to do the same with arrays ? 

Eg
 
```
var config = {
    plugins: {
        '$filter': 'phase',
        '$default': [{"key2":"val2"}],
        '$base':  [{"key1":"val1"}],
        local:  [{"key3":"val3"}],
    }
}
```

and have as a result the concatenated arrays ?

**Comment by netei** [comment]
It seems that it isn't possible with the current implementation to do that. Would you accept a pull request that would allow  for this ?

**Comment by patrickkettner** [comment]
Almost certainly, but I am not quire sure what you expect the value to be - the arrays being merged?

**Comment by netei** [comment]
I would expect to get 

```
console.log(store.get('/', { phase: 'local' }));
// [{"key1": "val1"}, {"key3", : "val3"}]

console.log(store.get('/', { phase: 'other' }));
// [{"key1": "val1"}, {"key2", : "val2"}]
```

**Comment by patrickkettner** [comment]
yeah, PR for that would be good
