### ISSUE TITLE
TLS cert/key data missing on Store.get(...) 

### ISSUE THREAD

**Issue by Jiropole** [hapijs/confidence#50]
I'm try to use the following TLS object to configure Hapi connections in my manifest. This pulls in a pair of Uint8Array objects, which I'm guessing is the problem.

```
const tlsOptions = {
    key: Fs.readFileSync('./config/certs/ssl-key.pem'),
    cert: Fs.readFileSync('./config/certs/ssl-cert.pem')
};
```

Unfortunately, when I extract the manifest using Store.get(...), the key and cert objects are now empty. Is this a bug, or a caveat I'm not understanding? Is there a suggested workaround? Thanks!

**Comment by mtharrison** [comment]
Not sure what the deal with converting to arrays is but maybe try sidestepping the issue of having `Buffer` objects in your store at all by specifying encoding when loading your cert/key?

```
const tlsOptions = {
    key: Fs.readFileSync('./config/certs/ssl-key.pem', 'utf-8'),
    cert: Fs.readFileSync('./config/certs/ssl-cert.pem', 'utf-8')
};
```

**Comment by Jiropole** [comment]
Uh, that's a brilliantly simple workaround! That did the job - thank you.

**Comment by mtharrison** [comment]
No probs.

**Comment by richardzyx** [comment]
Just a quick note that this workaround would only work with key/cert but not with pfx, since the converted string would be too large and node will throw a header too long exception. I haven't found a solution to pfx files, and feel free to share! Thanks!
