### ISSUE TITLE
Why Boom dependency ?

### ISSUE THREAD

**Issue by tlvenn** [hapijs/confidence#53]
Hi,

I am using confidence with some Hapi projects but as well with other client side projects (React Native) and I was surprised to see that the project is pulling `Boom` as dependency which makes no sense outside a server context.

Do we really need to encapsulate confidence error with Boom ? Could we make it pluggable and have a default behaviour that would not decorate error with Boom ?

Thanks.

**Comment by patrickkettner** [comment]
hi there!
its there because just because it was added to begin with when the module was created. I would be very open to having it be an option rather than a hard dep. PRs are welcomed
