### ISSUE TITLE
Support for loaders.

### ISSUE THREAD

**Issue by asaf** [hapijs/confidence#55]
Hey,

I'm not sure where this falls, but sometimes configuration needs file references,
Example can be the `tls` object of the connection object,

Does it make sense to make Confidence delegate property resolution by loaders ?

For example a config such:

```
tls: {
  key: "!file:/path/to/file"
}
```

And delegate to a file loader to resolve the key property on the final object?

The question is whether this falls in the scope of Confidence or not,
At the end Confidence designed to work with a Javascript object, not a JSON, so this sounds like more a job of the manifest reader,

So maybe this falls into Rejoice? I'm not exactly sure.

Thoughts?

**Comment by patrickkettner** [comment]
thanks for reaching out!
what other loaders do you imagine using?
I would personally lean away having loaders, due to the mental complexity, but am happy to be swayed

**Comment by asaf** [comment]
@patrickkettner 
I agree, I think Confidence should be kept slim as possible,

Please look at my PR #56,
It gives enough flexibility for custom needs (such as described here with TLS) for any value replacement.

**Comment by patrickkettner** [comment]
hey @asaf - sorry for not being clearer.
The point of my response was asking "what other loaders do you imagine using?". I can see a bit of the utility in this one PR, but I don't think its useful enough to add it without knowing that there are other good dieas for loaders as well.

so, what other loaders do you imagine existing?

**Comment by asaf** [comment]
Hey @patrickkettner 

You were clear enough,
I don't think we should support loaders because it's too complicated,

But having a Hapi server with SSL is a basic requirement and currently there is no way to set TLS ca using Confidence,

This PR solves SSL support using Confidence in a clean and slim way,

Do you have any other alternatives ?


Thanks.

**Comment by patrickkettner** [comment]
> I don't think we should support loaders because it's too complicated,

I am confused - are you going to close your PR?

> Do you have any other alternatives ?

I would have the function that outputs your JSON config blob, and within that grab the text of the file as a string

**Comment by asaf** [comment]
> I am confused - are you going to close your PR?

Have you reviewed the PR ? it says nothing about loaders, it just provides a simple and clean hook named `replaceValue` that replaces one value with another, look at the attached test, it leaves enough space without increasing complexity for replacing value.

> I would have the function that outputs your JSON config blob, and within that grab the text of the file as a string

Isn't it the responsibility of `Confidence` to take a template and produce the final configuration ?

btw, I see how loaders are complicated, but I really don't understand how a simple, optional, small hook that provides so much flexibility can be treated as 'complex'.

Thanks.

**Comment by mtharrison** [comment]
> there is no way to set TLS ca using Confidence

If your cert/key are pem encoded, you can you not just store them as a string in the store?

**Comment by patrickkettner** [comment]
@asaf - apologize, I mistook some of the test code for some of the PR.

I am hesitant to add the feature because it has not been needed by a large number of usecases up until this point. Have you tried what @mtharrison mentions?

**Comment by tlivings** [comment]
You could just use `shortstop`.

**Comment by augnin** [comment]
you can now use `$param` directive

```javascript
'use strict';

const Fs = require('fs');
const { promisify } = require('util');
const { Store } = require('confidence');

const run = async () => {

    const store = new Store({ cert : { $param: 'tls' }});
    const read = promisify(Fs.readFile);

    const buffer = await read('/path/to/file');

    store.get('/cert', { tls: buffer });
};

run();

```
