### ISSUE TITLE
multiple options for keys, not just values based on filters

### ISSUE THREAD

**Issue by danielb2** [hapijs/confidence#59]
What if I have:

``` javascript
{
  "plugins": {
    "$filter": "env",
    "$base": {
      "inert": {}
    },

    "qa": {
      "blipp": {}
    },
    "prod": {
      "good": {}
    },

    "$filter": "debug",
    "prod": {
      "debug": {}
    }
    "qa": {
      "extra-debug": {}
    }
  }
}


```

Right now it's very easy to have values change based on particular filters, however, keys at the same level doesn't seem to have the ability to change. For instance, I may want to have extra debugging plugin loaded for qa. It would be nice to have multiple filters at the same key level.

I don't believe this is possible atm?

( yes I realize in this instance you could argue that a debug plugin should be able to take options for debug levels, but this is an example and not the actual use-case, so please bear with me )

**Comment by danielb2** [comment]
I believe I can solve this with further nestings which gets a bit hairy

**Comment by danielb2** [comment]
The equivalent will look like this:

``` javascript
{
  "plugins": {
    "$filter": "env",
    "$base": {
      "inert": {}
    },

    "qa": {
      "$filter": "debug",
      "$default": {
        "blipp": {}
      },
      "$base": {
        "blipp": {}
      },
      "on": {
        "extra-debug": {}
      }
    },

    "prod": {
      "$filter": "debug",
      "$default": {
        "good": {}
      },
      "$base": {
        "good": {}
      },
      "on": {
        "debug": {}
      }
    }
  }
```

**Comment by danielb2** [comment]
I think the above is unnecessarily complex. Think there's a better way to solve this?

Basically prod should always load good, qa always load blipp. debug filter turns the appropriate filter on for each one.

**Comment by patrickkettner** [comment]
sorry for taking so long to get back to you on this. 

We are not interested in adding the ability to mutate keys to confidence. This would be best suited to a function that would generate your object, that is then passed to confidence
