### ISSUE TITLE
Allow pulling values from criteria into store

### ISSUE THREAD

**Issue by devinivy** [hapijs/confidence#74]
It would be nice to be able to take values in criteria and use them as parameters for store values.  Here's an example demonstrating how it might look,

```js
const store = new Confidence.Store({
    c: {
        $filter: 'size',
        big: { $param: 'maxSize' },
        small: 1,
        $default: 50
    }
});

store.get('/c', { size: 'big', maxSize: 200 }); // Evaluates to 200
```

If this sounds like a useful feature I would be happy to write some code for it.  Let me know if you'd like more information about my use-case.

**Comment by patrickkettner** [comment]
I feel like this sort of logic is something you would do with the result of the store, outside of confidence itself. My reasoning being that it is sort of unbounded in possibilities - truncating strings, array values, etc. I am going to pass on this being a feature now, but anyone else feel free to voice support for it below. If there is enough support I am willing to reconsider.

**Comment by devinivy** [comment]
@augnin with #81 and #82 landing, which allows setting values from environment variables, I would like to re-propose this feature, which would allow setting values additionally from criteria.

**Comment by Nargonath** [comment]
I don't have such use case right now but this feature feels useful. Perhaps we could see to standardize the format with the recent changes @augnin proposed. If you want to use the env as value you'd do: `$env.myEnv` perhaps we could follow the same syntax for your params proposal @devinivy aka:
```js
const store = new Confidence.Store({
    c: {
        $filter: 'size',
        big: '$params.maxSize',
        small: 1,
        $default: 50
    }
});

store.get('/c', { size: 'big', maxSize: 200 }); // Evaluates to 200
```
or flip it onto its head and use the object notation for @augnin proposal with the environment variable.

**Comment by augnin** [comment]
It probably makes sense to use object notation for env, with an additional $coerce operator. something like

```

**Comment by Nargonath** [comment]
Can't we use the same syntax in `$filter`? Allow for string or object so we don't break backward compat.
