### ISSUE TITLE
New maintainer?

### ISSUE THREAD

**Issue by hueniverse** [hapijs/confidence#75]
Project is not being maintained to hapi.js community standards. Too many open issues and PRs.

**Comment by csabapalfi** [comment]
Hey,

We rely on this library and a few of us at HomeAway.com want to maintain this repo.
More specifically: @knifir, @mannypamintuan and me.

How do we go about this?

Thanks,
Csaba

**Comment by hueniverse** [comment]
Ideally one of you it listed as lead and the others can be co-maintainers. This helps with decision making. The first step should be to reply to some open issues, PRs, etc and show some actual work done.

**Comment by orditeck** [comment]
Any update of this? I opened two pull requests, and https://github.com/hapijs/confidence/pull/78 would be really useful. cc @patrickkettner

**Comment by augnin** [comment]
@hueniverse I would like to maintain this project. for starters, I have taken #79 a little further with a little housekeeping and refactoring in #80.

**Comment by hueniverse** [comment]
@augnin great. All yours.
