### ISSUE TITLE
Either allow matching "$undefined" or any non-falsy criteria value

### ISSUE THREAD

**Issue by csabapalfi** [hapijs/confidence#77]
Currently there's no way to only have a $default value if the filtered criteria is undefined.

e.g. 
```json
{
  "$filter": "env.canBeUndefined",
  "$default": "env:canBeUndefined",
  "$undefined": "defaultValue"
}
```

(`env:` is shortstop syntax to get an env var)

We could also just have `$truthy`,`$falsy`,`$null`, etc but that's probably taking it too far.

An alternative to this is just manipulating criteria before passing it in but we just want to use `process.env` as it is.

I think #67 is about pretty much the same thing but in a different way.

**Comment by augnin** [comment]
hey @csabapalfi .. v4.0 handles a lot of this scenarios with `$env` and `$param` directives. have a look at the documentation and test cases. I am closing this for now. feel free to open this issue again, in case you think something is missing.
